"""Admin routes for managing fashion knowledge base and system settings."""
from flask import Blueprint, request, jsonify
from models.database import db
from models.user import User
from routes.auth import require_auth
from utils.fashion_kb import FASHION_KNOWLEDGE_BASE
import json
import os

admin_bp = Blueprint('admin', __name__)

def require_admin(f):
    """Decorator to require admin authentication."""
    @require_auth
    def decorated_function(*args, **kwargs):
        user = request.current_user
        if not user.is_admin:
            return jsonify({'error': 'Admin access required'}), 403
        return f(*args, **kwargs)
    return decorated_function

@admin_bp.route('/fashion-kb', methods=['GET'])
@require_admin
def get_fashion_kb():
    """Get the fashion knowledge base."""
    try:
        return jsonify({
            'success': True,
            'data': FASHION_KNOWLEDGE_BASE
        }), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@admin_bp.route('/fashion-kb', methods=['POST'])
@require_admin
def update_fashion_kb():
    """Update the fashion knowledge base."""
    try:
        data = request.get_json()
        kb_data = data.get('data')
        
        if not kb_data:
            return jsonify({'error': 'Knowledge base data is required'}), 400
        
        # Validate structure
        required_keys = ['color_matching', 'style_advice', 'occasions', 'fabric_guide', 'dress_styles', 'styling_tips']
        if not all(key in kb_data for key in required_keys):
            return jsonify({'error': 'Invalid knowledge base structure'}), 400
        
        # Backup current KB
        kb_file = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'utils', 'fashion_kb.py')
        backup_file = kb_file + '.backup'
        
        try:
            with open(kb_file, 'r', encoding='utf-8') as f:
                current_content = f.read()
            with open(backup_file, 'w', encoding='utf-8') as f:
                f.write(current_content)
        except Exception as e:
            print(f"Warning: Could not create backup: {e}")
        
        # Generate new fashion_kb.py file
        kb_content = f'''"""Fashion Knowledge Base for AI Agent - Style, Color Matching, and Occasions."""
# This file is auto-generated by admin panel. Manual edits may be overwritten.

FASHION_KNOWLEDGE_BASE = {json.dumps(kb_data, indent=4, ensure_ascii=False)}

def get_fashion_knowledge_base_text():
    """Get the full fashion knowledge base as formatted text for AI."""
    # Format dress styles
    necklines_text = "\\n".join([f"{{k.upper().replace('_', '-')}} NECKLINE:\\n{{v['description']}}\\nBest for: {{v['best_for']}}\\nOccasions: {{v['occasions']}}" for k, v in FASHION_KNOWLEDGE_BASE.get("dress_styles", {{}}).get("necklines", {{}}).items()])
    features_text = "\\n".join([f"{{k.upper().replace('_', '-')}} FEATURE:\\n{{v['description']}}\\nBest for: {{v['best_for']}}\\nOccasions: {{v['occasions']}}" for k, v in FASHION_KNOWLEDGE_BASE.get("dress_styles", {{}}).get("dress_features", {{}}).items()])
    men_styles_text = "\\n".join([f"{{k.upper().replace('_', '-')}} STYLE:\\n{{v['description']}}\\nBest for: {{v['best_for']}}\\nOccasions: {{v['occasions']}}" for k, v in FASHION_KNOWLEDGE_BASE.get("dress_styles", {{}}).get("men_styles", {{}}).items()])
    
    kb_text = """
FASHION KNOWLEDGE BASE FOR INSIGHTSHOP AI ASSISTANT
===================================================

COLOR MATCHING & COORDINATION:
{{color_matching}}

STYLE ADVICE:
{{style_advice}}

OCCASION-APPROPRIATE DRESSING:
{{occasions}}

FABRIC GUIDE:
{{fabric_guide}}

DRESS STYLES & NECKLINES (WOMEN):
{{necklines}}

DRESS FEATURES (WOMEN):
{{features}}

MEN'S STYLES:
{{men_styles}}

STYLING TIPS:
{{styling_tips}}
    """.format(
        color_matching=FASHION_KNOWLEDGE_BASE.get("color_matching", {{}}).get("basics", ""),
        style_advice="\\n".join([FASHION_KNOWLEDGE_BASE.get("style_advice", {{}}).get(k, "") for k in ["fit", "layering", "proportions"] if k in FASHION_KNOWLEDGE_BASE.get("style_advice", {{}})]),
        occasions="\\n".join([f"{{k.upper().replace('_', ' ')}}:\\n{{v}}" for k, v in FASHION_KNOWLEDGE_BASE.get("occasions", {{}}).items()]),
        fabric_guide="\\n".join([f"{{k.upper()}}:\\n{{v.get('description', '')}}\\nBest for: {{v.get('best_for', '')}}\\nCharacteristics: {{v.get('characteristics', '')}}" for k, v in FASHION_KNOWLEDGE_BASE.get("fabric_guide", {{}}).items()]),
        necklines=necklines_text,
        features=features_text,
        men_styles=men_styles_text,
        styling_tips="\\n".join([FASHION_KNOWLEDGE_BASE.get("styling_tips", {{}}).get(k, "") for k in ["build_wardrobe", "accessories", "seasonal_transitions"] if k in FASHION_KNOWLEDGE_BASE.get("styling_tips", {{}})])
    )
    return kb_text

def get_color_matching_advice(color):
    """Get color matching advice for a specific color."""
    color_lower = color.lower() if color else ""
    return FASHION_KNOWLEDGE_BASE.get("color_matching", {{}}).get("by_color", {{}}).get(color_lower, "This color pairs well with neutrals like black, white, gray, and navy for a classic look.")

def get_fabric_info(fabric_name):
    """Get information about a specific fabric."""
    if not fabric_name:
        return None
    
    fabric_lower = fabric_name.lower()
    for fabric_key, fabric_info in FASHION_KNOWLEDGE_BASE.get("fabric_guide", {{}}).items():
        if fabric_key in fabric_lower or fabric_lower in fabric_key:
            return fabric_info
    return None

def get_occasion_advice(occasion):
    """Get styling advice for a specific occasion."""
    occasion_lower = occasion.lower().replace(" ", "_")
    return FASHION_KNOWLEDGE_BASE.get("occasions", {{}}).get(occasion_lower, "Choose clothing that makes you feel confident and appropriate for the setting.")
'''
        
        # Write new file
        with open(kb_file, 'w', encoding='utf-8') as f:
            f.write(kb_content)
        
        # Reload the module (requires app restart for full effect, but we can try)
        import importlib
        import sys
        if 'utils.fashion_kb' in sys.modules:
            importlib.reload(sys.modules['utils.fashion_kb'])
        
        return jsonify({
            'success': True,
            'message': 'Fashion knowledge base updated successfully. Please restart the application for changes to take full effect.'
        }), 200
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': f'Failed to update knowledge base: {str(e)}'}), 500

@admin_bp.route('/fashion-kb/color', methods=['POST'])
@require_admin
def add_color_matching():
    """Add or update color matching advice."""
    try:
        data = request.get_json()
        color = data.get('color', '').lower()
        advice = data.get('advice', '')
        
        if not color or not advice:
            return jsonify({'error': 'Color and advice are required'}), 400
        
        # This would update the KB file - for now return success
        # Full implementation would modify the FASHION_KNOWLEDGE_BASE structure
        return jsonify({
            'success': True,
            'message': f'Color matching advice for {color} updated. Use the full KB update endpoint for permanent changes.'
        }), 200
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@admin_bp.route('/fashion-kb/fabric', methods=['POST'])
@require_admin
def add_fabric_info():
    """Add or update fabric information."""
    try:
        data = request.get_json()
        fabric_name = data.get('fabric_name', '').lower()
        fabric_info = data.get('fabric_info', {})
        
        if not fabric_name or not fabric_info:
            return jsonify({'error': 'Fabric name and info are required'}), 400
        
        return jsonify({
            'success': True,
            'message': f'Fabric info for {fabric_name} updated. Use the full KB update endpoint for permanent changes.'
        }), 200
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@admin_bp.route('/users', methods=['GET'])
@require_admin
def list_users():
    """List all users (admin only)."""
    try:
        users = User.query.all()
        return jsonify({
            'success': True,
            'users': [user.to_dict() for user in users]
        }), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@admin_bp.route('/users/<int:user_id>/admin', methods=['PUT'])
@require_admin
def toggle_admin(user_id):
    """Toggle admin status for a user."""
    try:
        user = User.query.get(user_id)
        if not user:
            return jsonify({'error': 'User not found'}), 404
        
        data = request.get_json()
        is_admin = data.get('is_admin', False)
        
        user.is_admin = is_admin
        db.session.commit()
        
        return jsonify({
            'success': True,
            'message': f'Admin status updated for {user.email}',
            'user': user.to_dict()
        }), 200
        
    except Exception as e:
        db.session.rollback()
        return jsonify({'error': str(e)}), 500

